name: Run Cypress Tests Manually

on:
  workflow_dispatch:
    inputs:
      cypress_user:
        description: 'Inserisci lo username per SauceDemo'
        required: true
        default: 'standard_user'
        type: string
      cypress_password:
        description: 'Inserisci la password per SauceDemo'
        required: true
        default: 'secret_sauce'
        type: string

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Scarica il codice della repository direttamente nella cartella principale
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configura Node 16 (stabile per questa struttura)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # 3. Installa i pacchetti partendo dalla radice della repository
      - name: Install Dependencies
        run: npm ci

      # 4. Lancia il file di test specifico che si trova in cypress/e2e
      - name: Run Cypress Tests
        run: npx cypress run --spec "cypress/e2e/1_6_login_visual_user_checkout-step-two.cy.js"
        env:
          CYPRESS_CYPRESS_USER: ${{ github.event.inputs.cypress_user }}
          CYPRESS_CYPRESS_PASSWORD: ${{ github.event.inputs.cypress_password }}

      # 5. Salva i video dell'esecuzione così potrai scaricarli a fine run
      - name: Upload Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/screenshots/
            cypress/videos/
